name: lucid_validation
description: "A Dart/Flutter package for building strongly typed validation rules inspired by FluentValidation and created by the Flutterando community."
repository: https://github.com/Flutterando/lucid_validation
homepage: https://pub.dev/documentation/lucid_validation/latest/

version: 0.0.6

environment:
  sdk: ">=3.0.0 <4.0.0"

# dependencies:


dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.8
